name: amazonVideoGames
user_count: 31027
item_count: 33899

# attribute info
user_attr:
  have: false
item_attr:
  have: true
  attr_type_num: 3
  attr_dim_list: [ 14, 52, 10 ]
  attr_type_list: [ 1, 1, 0 ] # 0 means single-label attribute and 1 means multi-label attributes

# model settings
AI:
  epoch_num: 300 # epoch times
  iter_num: 10 # iter times
  free_emb_dim: 32 # free embedding dim
  learning_rate: 0.0005 # learning rate
  batch_size: 5120
  gamma: 0.001
  lambda1: 0.001
  lambda2: 0.001
  attr_union_dim: 32
  gcn_layer: 3
  neg_item_num: 5

IR-Train:
  epoch_num: 300 # epoch times
  iter_num: 10 # iter times
  free_emb_dim: 32 # free embedding dim
  learning_rate: 0.0005 # learning rate
  batch_size: 5120
  gamma: 0.001
  lambda1: 0.001
  lambda2: 0.001
  attr_union_dim: 32
  gcn_layer: 3
  neg_item_num: 5

IR-Test:
  free_emb_dim: 32 # free embedding dim
  gamma: 0.001
  lambda1: 0.001
  lambda2: 0.001
  attr_union_dim: 32
  gcn_layer: 3
  neg_item_num: 5
  test_topks: [ 5,10,15,20,25,30,35,40,45,50 ]

# baselines for item recommendation
BPR-MF:
  epoch_num: 300

NGCF:
  epoch_num: 300

# baselines for attribute inference
LP:
  epoch_num: 300
  loss_threshold_for_save_pth: 1.0

Semi-GCN:
  epoch_num: 300
