name: movielens-20M
user_count: 138493
item_count: 27278

epoch_num: 100 # epoch times
iter_num: 10 # iter times
free_emb_dim: 32 # free embedding dim
learning_rate: 0.001 # learning rate
batch_size: 153600
gamma: 0.001
lambda1: 0.01
lambda2: 0.001
attr_union_dim: 20
gcn_layer: 2
neg_item_num: 5
test_topks: [5,10,15,20,25,30,35,40,45,50]

user_attr:
  have: false
item_attr:
  have: true
  attr_type_num: 1
  attr_dim_list: [20]
  attr_type_list: [1] # 0 means single-label attribute and 1 means multi-label attributes


LP:
  epoch_num: 50
  loss_threshold: 0.01
  select_count: 1000
  knn: 20

Semi-GCN:
  epoch_num: 50
  gcn_layer: 2
  attr_union_dim: 20
  layer_dim_list: [20, 20, 20, 20]
  learning_rate: 0.05
